# Generated by Django 2.2 on 2020-03-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
    ]
